#!/bin/bash
ip_source=$1
function hoplistgeo () {
    mtr -r -n ${ip_source} | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | xargs -i geoiplookup {}
}

function ipinfo  () {
    geoiplookup ${ip_source}
}

echo `echo [ { \"Target\": [ \"${ip_source}\", \"$(ipinfo)\" ], \"hops\": \"$(hoplistgeo)\" } ]`